version: "3.9"                              # 3.9 is stable version of DOCKER-COMPOSE

services:
  ft_mariadb:
    build: ./requirements/mariadb
    container_name: inception_mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - ../secrets/.env
    restart: unless-stopped

  ft_wordpress:
    build: ./requirements/wordpress
    container_name: inception_wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - ft_mariadb
    networks:
      - inception
    env_file:
      - ../secrets/.env
    restart: unless-stopped
    
  ft_nginx:
    build: ./requirements/nginx
    container_name: inception_nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - ft_wordpress
    networks:
      - inception
    env_file:
      - ../secrets/.env
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vsyutkin/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vsyutkin/data/wordpress

networks:
  inception:
    driver: bridge